name: Build and Release

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  check_version:
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.check.outputs.should_release }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed to fetch tags
      - id: check
        working-directory: ./app
        run: |
          VERSION=$(node -p "require('./package.json').version")
          TAG="v$VERSION"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Skipping release."
            echo "should_release=false" >> $GITHUB_OUTPUT
          else
            echo "Tag $TAG does not exist. We should release!"
            echo "should_release=true" >> $GITHUB_OUTPUT
            echo "version=$TAG" >> $GITHUB_OUTPUT
          fi

  create_tag:
    needs: check_version
    if: needs.check_version.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create and Push Git Tag
        run: |
          git tag ${{ needs.check_version.outputs.version }}
          git push origin ${{ needs.check_version.outputs.version }}

  build:
    needs: [check_version, create_tag]
    if: needs.check_version.outputs.should_release == 'true'
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.check_version.outputs.version }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Install Python dependencies
        run: |
          uv venv
          uv pip install -r pyproject.toml
          uv pip install pyinstaller

      - name: Build Python Executable
        env:
          APP_USERNAME: ${{ secrets.APP_USERNAME }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          APP_URL: ${{ secrets.APP_URL }}
        run: |
          # Crear archivo .env con los secretos de GitHub para empaquetarlo
          echo "APP_USERNAME=$APP_USERNAME" > .env
          echo "APP_PASSWORD=$APP_PASSWORD" >> .env
          echo "APP_URL=$APP_URL" >> .env

          # Activamos entorno virtual y empaquetamos
          source .venv/bin/activate
          pyinstaller --onefile --add-data ".env:." src/cli.py
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install Node dependencies
        working-directory: ./app
        run: npm install

      - name: Inject GH_TOKEN for AutoUpdater
        working-directory: ./app
        env:
          MY_GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: sed -i '' "s|%%GH_TOKEN%%|${MY_GH_TOKEN}|g" main.js

      - name: Build and Publish Electron App
        working-directory: ./app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EP_DRAFT: "false"
          CSC_IDENTITY_AUTO_DISCOVERY: "false"
        run: npm run build:mac -- -p always
        shell: bash
